### ISSUE TITLE
请问这个还能用吗?

### ISSUE THREAD

**Issue by wxydejoy** [mohuishou/notion-blog-actions#1]
大佬带带

**Comment by mohuishou** [comment]
可以的，我现在正在用，这是优化过的 v2 版本了

**Comment by wxydejoy** [comment]
大佬帮忙看看
![image](https://user-images.githubusercontent.com/81625961/196829992-2132116d-7e7d-4228-bb02-adbdc3369c2a.png)
Current runner version: '[2](https://github.com/wxydejoy/blog/actions/runs/3278198954/jobs/5396323827#step:1:2).298.2'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@master' (SHA:1f9a0c22da41e[6](https://github.com/wxydejoy/blog/actions/runs/3278198954/jobs/5396323827#step:1:7)ebfa534300ef656657ea2c6707)
Download action repository 'mohuishou/notion-blog-actions@main' (SHA:1af8d607224f35c4ad[28](https://github.com/wxydejoy/blog/actions/runs/3278198954/jobs/5396323827#step:1:32)d4a410544a5851bc6a2e)
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/_actions/mohuishou/notion-blog-actions/main/notion'. Did you forget to run actions/checkout before running your local action?

**Comment by mohuishou** [comment]
改成这样试试 `mohuishou/notion-blog-actions@v2.0.0`

**Comment by wxydejoy** [comment]
还是不行
大佬帮我看看配置
```yaml

# on: [workflow_dispatch, watch]
on:
  push:
    branches:
      - main
      #2020年10月后github新建仓库默认分支改为main，注意更改

name: notion

jobs:
  notion:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: main

    - uses: mohuishou/notion-blog-actions@v2.0.0
      with:
        # token: ${{ secrets.NOTION_TOKEN }}
        token_v2: ${{ secrets.NOTION_TOKEN_V2 }}
        space_id: "8b9d4c6f-6127-4b20-84c8-4dae892e5e4b"
        database_id: "80137e2d105745dbbd9c432e706112d5"
        output: "./tmp/"

    - name: "migrate image"
      uses: mohuishou/notion-blog-actions/migrate@main
      with:
        input: "./tmp/*.md"

    - name: "cp md files"
      run: |
        cp -f tmp/*.md source/_posts/notion/
        rm -rf tmp

    - name: git setting
      run: |
        git config --global user.email "1798923421@qq.com"
        git config --global user.name "wxydejoy"
      
    - name: update blog
      run: |
        git add source
        git commit -m "feat: auto update by notion sync"
        git push
```
